language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build endoflife_date.gemspec
  - gem install ./endoflife_date-0.10.1-pre.0.gem
