---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.OAPICF_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: cliffano/command-docker-action@v1.3.0
        with:
          command: 'make ci'
          image: cliffano/studio:2.11.1
      - run: npm install -g gh-pages
      - run: CACHE_DIR=/tmp gh-pages --dist doc/ --user "pakkunbot <blah+pakkun@cliffano.com>" --repo "https://cliffano:${{ secrets.OAPICF_GITHUB_TOKEN }}@github.com/oapicf/endoflife.date-api-clients.git"
