name: Publish API Documentation
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          ref: main
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: make deps init-spec doc-latest doc-version
      - run: >-
          CACHE_DIR=/tmp gh-pages --dist doc/ --user "pakkunbot
          <blah+pakkun@cliffano.com>" --repo "https://cliffano:${{
          secrets.STUDIO_GITHUB_TOKEN
          }}@github.com/oapicf/endoflife.date-api-clients.git"
